import React from "react";
import { prisma } from "@/lib/db";
import { jsonToHtml } from "@/lib/export-utils";
import { notFound } from "next/navigation";
import { Badge } from "@workspace/ui/components/badge";
import { Tags, Calendar, Share2, Globe } from "lucide-react";
import "@/components/note-styles.css";
import { ThemeToggle } from "@/components/theme-toggle";

interface PageProps {
  params: Promise<{ token: string }>;
}

export default async function SharedNotePage({ params }: PageProps) {
  const { token } = await params;

  const sharedNote = await prisma.sharedNote.findUnique({
    where: { token },
    include: { note: { include: { author: { select: { email: true } } } } },
  });

  if (!sharedNote) {
    notFound();
  }

  if (!sharedNote.is_public) {
    notFound();
  }

  if (sharedNote.expires_at && new Date(sharedNote.expires_at) < new Date()) {
    notFound();
  }

  const contentHtml = jsonToHtml(sharedNote.note.content, undefined, false);

  return (
    <div className="bg-background text-foreground selection:bg-primary/20 min-h-screen">
      {}
      <header className="bg-background/80 sticky top-0 z-10 w-full border-b backdrop-blur-md">
        <div className="mx-auto flex h-14 max-w-5xl items-center justify-between px-6">
          <div className="flex items-center gap-2">
            <div className="bg-primary shadow-primary/20 flex h-8 w-8 items-center justify-center rounded-lg shadow-lg">
              <Share2 className="size-4 text-white" />
            </div>
            <span className="text-sm font-semibold tracking-tight">
              Shared via Lume Notes
            </span>
          </div>
          <div className="flex items-center gap-4">
            <div className="text-muted-foreground bg-primary/5 border-primary/10 hover:bg-primary/10 flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs transition-colors">
              <Globe className="text-primary size-3" />
              Public View Only
            </div>
            <ThemeToggle />
          </div>
        </div>
      </header>

      <main className="animate-in fade-in slide-in-from-bottom-4 mx-auto max-w-4xl px-6 py-12 duration-700 md:py-20">
        <div className="mb-12 space-y-4">
          <h1 className="text-foreground text-4xl leading-[1.1] font-extrabold tracking-tight md:text-5xl">
            {sharedNote.note.title}
          </h1>

          {sharedNote.note.tags && sharedNote.note.tags.length > 0 && (
            <div className="flex flex-wrap items-center gap-2 border-b pb-8">
              {sharedNote.note.tags.map((tag: string, i: number) => (
                <Badge
                  key={i}
                  variant="secondary"
                  className="bg-primary/5 text-primary hover:bg-primary border-primary/10 cursor-default px-3 py-1 text-[11px] font-bold tracking-wide uppercase transition-all hover:text-white"
                >
                  {tag}
                </Badge>
              ))}
            </div>
          )}
        </div>

        <article className="max-w-none">
          <div
            className="tiptap animate-in fade-in slide-in-from-bottom-2 delay-150 duration-1000"
            dangerouslySetInnerHTML={{ __html: contentHtml }}
          />
        </article>

        <footer className="mt-20 border-t pt-12 pb-24 text-center">
          <p className="text-muted-foreground flex flex-col items-center gap-4 text-sm">
            <span className="font-serif italic opacity-60">
              Note generated by Lume Notes
            </span>
            <a
              href="/"
              className="bg-foreground text-background shadow-foreground/10 rounded-full px-6 py-2.5 text-xs font-bold tracking-wide shadow-xl transition-all hover:scale-105 active:scale-95"
            >
              GET STARTED FOR FREE
            </a>
          </p>
        </footer>
      </main>
    </div>
  );
}
