import React from "react";
import { prisma } from "@/lib/db";
import { jsonToHtml } from "@/lib/export-utils";
import { notFound } from "next/navigation";
import { Badge } from "@workspace/ui/components/badge";
import { Tags, Calendar, Share2, Globe } from "lucide-react";
import "@/components/note-styles.css";
import { ThemeToggle } from "@/components/theme-toggle";

interface PageProps {
  params: Promise<{ token: string }>;
}

export default async function SharedNotePage({ params }: PageProps) {
  const { token } = await params;

  const sharedNote = await prisma.sharedNote.findUnique({
    where: { token },
    include: { note: { include: { author: { select: { email: true } } } } },
  });

  if (!sharedNote) {
    notFound();
  }

  if (!sharedNote.is_public) {
    notFound();
  }

  if (sharedNote.expires_at && new Date(sharedNote.expires_at) < new Date()) {
    notFound();
  }

  
  const contentHtml = jsonToHtml(
    sharedNote.note.content,
    undefined,
    false
  );

  return (
    <div className="bg-background text-foreground min-h-screen selection:bg-primary/20">
      {}
      <header className="sticky top-0 z-10 w-full border-b bg-background/80 backdrop-blur-md">
        <div className="mx-auto flex h-14 max-w-5xl items-center justify-between px-6">
          <div className="flex items-center gap-2">
            <div className="bg-primary flex h-8 w-8 items-center justify-center rounded-lg shadow-lg shadow-primary/20">
              <Share2 className="text-white size-4" />
            </div>
            <span className="text-sm font-semibold tracking-tight">Shared via Lume Notes</span>
          </div>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2 text-xs text-muted-foreground bg-primary/5 px-3 py-1.5 rounded-full border border-primary/10 transition-colors hover:bg-primary/10">
              <Globe className="size-3 text-primary" />
              Public View Only
            </div>
            <ThemeToggle />
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-12 md:py-20 animate-in fade-in slide-in-from-bottom-4 duration-700">
        <div className="mb-12 space-y-4">
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-foreground leading-[1.1]">
            {sharedNote.note.title}
          </h1>
          
          {sharedNote.note.tags && sharedNote.note.tags.length > 0 && (
            <div className="flex flex-wrap items-center gap-2 border-b pb-8">
              {sharedNote.note.tags.map((tag: string, i: number) => (
                <Badge 
                  key={i} 
                  variant="secondary" 
                  className="px-3 py-1 text-[11px] font-bold uppercase tracking-wide bg-primary/5 text-primary hover:bg-primary hover:text-white border-primary/10 transition-all cursor-default"
                >
                  {tag}
                </Badge>
              ))}
            </div>
          )}
        </div>

        <article className="max-w-none">
          <div 
            className="tiptap animate-in fade-in slide-in-from-bottom-2 duration-1000 delay-150" 
            dangerouslySetInnerHTML={{ __html: contentHtml }} 
          />
        </article>

        <footer className="mt-20 border-t pt-12 pb-24 text-center">
          <p className="text-muted-foreground text-sm flex flex-col items-center gap-4">
             <span className="opacity-60 italic font-serif">Note generated by Lume Notes</span>
             <a 
               href="/" 
               className="bg-foreground text-background px-6 py-2.5 rounded-full font-bold text-xs tracking-wide transition-all hover:scale-105 active:scale-95 shadow-xl shadow-foreground/10"
             >
               GET STARTED FOR FREE
             </a>
          </p>
        </footer>
      </main>
    </div>
  );
}
